name: SSH

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Install tmate
        run: |
          sudo apt update
          sudo apt install -y tmate curl

      - name: Start tmate and send SSH to Telegram
        env:
          BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready

          SSH_CMD=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')
          WEB_CMD=$(tmate -S /tmp/tmate.sock display -p '#{tmate_web}')

          MESSAGE="🔐 GitHub Actions SSH Ready SSH: $SSH_CMD  Web: $WEB_CMD"

          curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
            -d chat_id="${CHAT_ID}" \
            --data-urlencode text="$MESSAGE" > /dev/null

          # keep runner alive
          sleep infinity
